import { Site, Worker, SafetyAlert } from '../types';

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-phx-01',
    name: 'Phoenix Metro Rail & Sky Harbor Expansion',
    city: 'Phoenix',
    state: 'AZ',
    lat: 33.4352,
    lng: -112.0101,
    zoom: 16,
    currentTemp: 41.8,
    peakTempToday: 44.5,
    humidity: 18,
    solarRadiation: 940,
    heatIndex: 43.6,
    workerCount: 14,
    atRiskCount: 6,
    extremeCount: 2,
    cautionCount: 5,
    safeCount: 3,
    coolZoneStations: [
      {
        id: 'cz-phx-1',
        name: 'North Air-Con Cooling Trailer #1',
        lat: 33.4365,
        lng: -112.0085,
        capacity: 15,
        occupied: 8,
        hasMisting: true,
        waterSuppliesLitres: 140,
      },
      {
        id: 'cz-phx-2',
        name: 'South Shaded Misting Pavilion',
        lat: 33.4338,
        lng: -112.0118,
        capacity: 25,
        occupied: 12,
        hasMisting: true,
        waterSuppliesLitres: 280,
      },
    ],
    zones: [
      { id: 'z-phx-1', name: 'Open Trench & Track Laying', type: 'trench', currentTemp: 44.2, riskLevel: 'extreme', workerCount: 4 },
      { id: 'z-phx-2', name: 'Terminal Roof Deck Steel Work', type: 'roof_deck', currentTemp: 43.1, riskLevel: 'danger', workerCount: 5 },
      { id: 'z-phx-3', name: 'Heavy Equipment Staging', type: 'heavy_machinery', currentTemp: 39.4, riskLevel: 'caution', workerCount: 3 },
      { id: 'z-phx-4', name: 'North Shade Canopy', type: 'shade_station', currentTemp: 28.5, riskLevel: 'safe', workerCount: 2 },
    ],
  },
  {
    id: 'site-sj-02',
    name: 'Diridon Station Urban Transit Hub',
    city: 'San Jose',
    state: 'CA',
    lat: 37.3297,
    lng: -121.9015,
    zoom: 16,
    currentTemp: 34.2,
    peakTempToday: 36.8,
    humidity: 42,
    solarRadiation: 780,
    heatIndex: 35.8,
    workerCount: 12,
    atRiskCount: 2,
    extremeCount: 0,
    cautionCount: 6,
    safeCount: 4,
    coolZoneStations: [
      {
        id: 'cz-sj-1',
        name: 'Diridon West Misting Tent',
        lat: 37.3310,
        lng: -121.9030,
        capacity: 20,
        occupied: 4,
        hasMisting: true,
        waterSuppliesLitres: 200,
      },
    ],
    zones: [
      { id: 'z-sj-1', name: 'Asphalt Paving Section A', type: 'open_field', currentTemp: 38.6, riskLevel: 'danger', workerCount: 3 },
      { id: 'z-sj-2', name: 'Foundation Framing', type: 'open_field', currentTemp: 34.5, riskLevel: 'caution', workerCount: 5 },
      { id: 'z-sj-3', name: 'Underground Concourse', type: 'shade_station', currentTemp: 24.2, riskLevel: 'safe', workerCount: 4 },
    ],
  },
  {
    id: 'site-tx-03',
    name: 'Austin Gigafactory Solar Farm Extension',
    city: 'Austin',
    state: 'TX',
    lat: 30.2223,
    lng: -97.6171,
    zoom: 15,
    currentTemp: 39.5,
    peakTempToday: 42.1,
    humidity: 58,
    solarRadiation: 890,
    heatIndex: 44.8,
    workerCount: 10,
    atRiskCount: 5,
    extremeCount: 2,
    cautionCount: 3,
    safeCount: 2,
    coolZoneStations: [
      {
        id: 'cz-tx-1',
        name: 'Field Hydration Post Delta',
        lat: 30.2240,
        lng: -97.6150,
        capacity: 30,
        occupied: 14,
        hasMisting: true,
        waterSuppliesLitres: 450,
      },
    ],
    zones: [
      { id: 'z-tx-1', name: 'Solar Array Grid B (Reflective)', type: 'open_field', currentTemp: 45.0, riskLevel: 'extreme', workerCount: 4 },
      { id: 'z-tx-2', name: 'Substation Inverter Install', type: 'heavy_machinery', currentTemp: 40.2, riskLevel: 'danger', workerCount: 3 },
      { id: 'z-tx-3', name: 'Perimeter Trenching', type: 'trench', currentTemp: 36.8, riskLevel: 'caution', workerCount: 3 },
    ],
  },
];

export const INITIAL_WORKERS: Worker[] = [
  {
    id: 'w-101',
    name: 'Marcus Vance',
    role: 'Lead Rebar Technician',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (602) 555-0142',
    ppeType: 'Class 3 High-Vis Vest + Hardhat with Neck Shade',
    currentTemp: 44.6,
    feelsLikeTemp: 47.2,
    heatIndex: 46.8,
    customThreshold: 38.0,
    status: 'extreme',
    location: { lat: 33.4358, lng: -112.0094, siteId: 'site-phx-01', zoneName: 'Open Trench & Track Laying' },
    vitals: { heartRate: 142, bodyTemp: 38.9, sweatRate: 'high', hydrationLevel: 32, heatStrainIndex: 8.8 },
    timeInSunMinutes: 215,
    lastCheckIn: new Date(Date.now() - 4 * 60000).toISOString(),
    breakRequested: true,
    breakRequestTime: new Date(Date.now() - 6 * 60000).toISOString(),
    batteryLevel: 88,
  },
  {
    id: 'w-102',
    name: 'Elena Rostova',
    role: 'Structural Welder',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (602) 555-0189',
    ppeType: 'Flame-Resistant Coveralls + Welding Hood',
    currentTemp: 43.8,
    feelsLikeTemp: 46.0,
    heatIndex: 45.4,
    customThreshold: 37.5,
    status: 'extreme',
    location: { lat: 33.4361, lng: -112.0108, siteId: 'site-phx-01', zoneName: 'Terminal Roof Deck Steel Work' },
    vitals: { heartRate: 136, bodyTemp: 38.6, sweatRate: 'high', hydrationLevel: 41, heatStrainIndex: 8.2 },
    timeInSunMinutes: 190,
    lastCheckIn: new Date(Date.now() - 2 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 94,
  },
  {
    id: 'w-103',
    name: 'Carlos Mendez',
    role: 'Concrete Finisher',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (602) 555-0211',
    ppeType: 'Safety Helmet + UV Cooling Gaiter',
    currentTemp: 40.5,
    feelsLikeTemp: 42.8,
    heatIndex: 42.1,
    customThreshold: 38.5,
    status: 'danger',
    location: { lat: 33.4346, lng: -112.0099, siteId: 'site-phx-01', zoneName: 'Terminal Roof Deck Steel Work' },
    vitals: { heartRate: 122, bodyTemp: 38.1, sweatRate: 'high', hydrationLevel: 55, heatStrainIndex: 6.9 },
    timeInSunMinutes: 160,
    lastCheckIn: new Date(Date.now() - 8 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 76,
  },
  {
    id: 'w-104',
    name: 'Devon Washington',
    role: 'Crane Operator',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (602) 555-0304',
    ppeType: 'Hardhat + Polarized Safety Glasses',
    currentTemp: 35.8,
    feelsLikeTemp: 37.0,
    heatIndex: 36.4,
    customThreshold: 39.0,
    status: 'caution',
    location: { lat: 33.4370, lng: -112.0112, siteId: 'site-phx-01', zoneName: 'Heavy Equipment Staging' },
    vitals: { heartRate: 98, bodyTemp: 37.4, sweatRate: 'moderate', hydrationLevel: 72, heatStrainIndex: 4.1 },
    timeInSunMinutes: 110,
    lastCheckIn: new Date(Date.now() - 12 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 82,
  },
  {
    id: 'w-105',
    name: 'Aisha Al-Mansoor',
    role: 'Quality & Survey Inspector',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (602) 555-0455',
    ppeType: 'Class 2 Vest + Misting Backpack',
    currentTemp: 31.0,
    feelsLikeTemp: 31.8,
    heatIndex: 31.2,
    customThreshold: 38.0,
    status: 'safe',
    location: { lat: 33.4363, lng: -112.0087, siteId: 'site-phx-01', zoneName: 'North Shade Canopy' },
    vitals: { heartRate: 84, bodyTemp: 37.0, sweatRate: 'low', hydrationLevel: 88, heatStrainIndex: 2.2 },
    timeInSunMinutes: 45,
    lastCheckIn: new Date(Date.now() - 1 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 98,
  },
  // San Jose Workers
  {
    id: 'w-201',
    name: 'Mateo Morales',
    role: 'Asphalt Paver Lead',
    siteId: 'site-sj-02',
    siteName: 'Diridon Station Transit Hub',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (408) 555-8812',
    ppeType: 'High-Temp Boots + Cooling Neck Wrap',
    currentTemp: 39.1,
    feelsLikeTemp: 41.5,
    heatIndex: 40.8,
    customThreshold: 37.0,
    status: 'danger',
    location: { lat: 37.3292, lng: -121.9022, siteId: 'site-sj-02', zoneName: 'Asphalt Paving Section A' },
    vitals: { heartRate: 128, bodyTemp: 38.3, sweatRate: 'high', hydrationLevel: 48, heatStrainIndex: 7.4 },
    timeInSunMinutes: 175,
    lastCheckIn: new Date(Date.now() - 5 * 60000).toISOString(),
    breakRequested: true,
    breakRequestTime: new Date(Date.now() - 3 * 60000).toISOString(),
    batteryLevel: 67,
  },
  {
    id: 'w-202',
    name: 'Sarah Jenkins',
    role: 'Electrical Foreman',
    siteId: 'site-sj-02',
    siteName: 'Diridon Station Transit Hub',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (408) 555-8845',
    ppeType: 'Dielectric Hardhat + High-Vis Vest',
    currentTemp: 34.6,
    feelsLikeTemp: 35.8,
    heatIndex: 35.2,
    customThreshold: 38.0,
    status: 'caution',
    location: { lat: 37.3301, lng: -121.9009, siteId: 'site-sj-02', zoneName: 'Foundation Framing' },
    vitals: { heartRate: 102, bodyTemp: 37.6, sweatRate: 'moderate', hydrationLevel: 68, heatStrainIndex: 4.8 },
    timeInSunMinutes: 130,
    lastCheckIn: new Date(Date.now() - 9 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 91,
  },
  {
    id: 'w-203',
    name: 'Li Wei',
    role: 'Concourse Mason',
    siteId: 'site-sj-02',
    siteName: 'Diridon Station Transit Hub',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (408) 555-8890',
    ppeType: 'Dust Respirator + Hardhat',
    currentTemp: 25.1,
    feelsLikeTemp: 25.4,
    heatIndex: 25.0,
    customThreshold: 38.0,
    status: 'safe',
    location: { lat: 37.3312, lng: -121.9028, siteId: 'site-sj-02', zoneName: 'Underground Concourse' },
    vitals: { heartRate: 78, bodyTemp: 36.8, sweatRate: 'low', hydrationLevel: 92, heatStrainIndex: 1.8 },
    timeInSunMinutes: 30,
    lastCheckIn: new Date(Date.now() - 15 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 85,
  },
  // Texas Solar Farm Workers
  {
    id: 'w-301',
    name: 'Jackson Reed',
    role: 'Solar Photovoltaic Specialist',
    siteId: 'site-tx-03',
    siteName: 'Austin Gigafactory Solar Farm',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (512) 555-6712',
    ppeType: 'UV Anti-Glare Face Shield + Solar Suit',
    currentTemp: 45.3,
    feelsLikeTemp: 49.6,
    heatIndex: 48.9,
    customThreshold: 38.0,
    status: 'extreme',
    location: { lat: 30.2228, lng: -97.6165, siteId: 'site-tx-03', zoneName: 'Solar Array Grid B (Reflective)' },
    vitals: { heartRate: 148, bodyTemp: 39.1, sweatRate: 'high', hydrationLevel: 28, heatStrainIndex: 9.4 },
    timeInSunMinutes: 240,
    lastCheckIn: new Date(Date.now() - 1 * 60000).toISOString(),
    breakRequested: true,
    breakRequestTime: new Date(Date.now() - 2 * 60000).toISOString(),
    batteryLevel: 54,
  },
  {
    id: 'w-302',
    name: 'Tanya Morales',
    role: 'Inverter Technician',
    siteId: 'site-tx-03',
    siteName: 'Austin Gigafactory Solar Farm',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    phone: '+1 (512) 555-6788',
    ppeType: 'Arc Flash Shield + High-Vis Harness',
    currentTemp: 40.8,
    feelsLikeTemp: 44.2,
    heatIndex: 43.5,
    customThreshold: 37.5,
    status: 'danger',
    location: { lat: 30.2215, lng: -97.6180, siteId: 'site-tx-03', zoneName: 'Substation Inverter Install' },
    vitals: { heartRate: 125, bodyTemp: 38.2, sweatRate: 'high', hydrationLevel: 50, heatStrainIndex: 7.1 },
    timeInSunMinutes: 180,
    lastCheckIn: new Date(Date.now() - 7 * 60000).toISOString(),
    breakRequested: false,
    batteryLevel: 79,
  },
];

export const INITIAL_ALERTS: SafetyAlert[] = [
  {
    id: 'alt-901',
    workerId: 'w-301',
    workerName: 'Jackson Reed',
    siteId: 'site-tx-03',
    siteName: 'Austin Gigafactory Solar Farm',
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    severity: 'extreme',
    type: 'emergency_sos',
    title: 'CRITICAL: Heat Strain SOS Triggered',
    message: 'Worker Jackson Reed registered 45.3°C ambient with core heat strain index 9.4. Break urgently requested.',
    temperature: 45.3,
    threshold: 38.0,
    acknowledged: false,
    resolved: false,
  },
  {
    id: 'alt-902',
    workerId: 'w-101',
    workerName: 'Marcus Vance',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    timestamp: new Date(Date.now() - 6 * 60000).toISOString(),
    severity: 'extreme',
    type: 'threshold_exceeded',
    title: 'Extreme Heat Exceedance',
    message: 'Marcus Vance has exceeded safety threshold (44.6°C vs 38.0°C limit) in Open Trench zone for > 35 min.',
    temperature: 44.6,
    threshold: 38.0,
    acknowledged: false,
    resolved: false,
  },
  {
    id: 'alt-903',
    workerId: 'w-201',
    workerName: 'Mateo Morales',
    siteId: 'site-sj-02',
    siteName: 'Diridon Station Transit Hub',
    timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
    severity: 'danger',
    type: 'break_requested',
    title: 'Worker Break Request',
    message: 'Mateo Morales requested 15-min cooling shelter rotation due to elevated asphalt surface radiance (39.1°C).',
    temperature: 39.1,
    threshold: 37.0,
    acknowledged: true,
    acknowledgedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    acknowledgedBy: 'Safety Supervisor - Teja',
    resolved: false,
  },
  {
    id: 'alt-904',
    workerId: 'w-102',
    workerName: 'Elena Rostova',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    severity: 'danger',
    type: 'hydration_needed',
    title: 'Hydration Depletion Alert',
    message: 'Elena Rostova hydration estimated at 41% after 190 minutes in direct sun. Sentinel dispatched hydration prompt.',
    temperature: 43.8,
    threshold: 37.5,
    acknowledged: true,
    acknowledgedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    acknowledgedBy: 'System Auto-Sentinel',
    resolved: true,
    resolvedAt: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'alt-905',
    siteId: 'site-phx-01',
    siteName: 'Phoenix Metro Rail & Sky Harbor',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    severity: 'caution',
    type: 'heat_spike',
    title: 'Microclimate Heat Island Spike',
    message: 'FortyGuard urban heat tile detected +3.4°C localized surge around Terminal Roof Deck area.',
    temperature: 41.8,
    acknowledged: true,
    acknowledgedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    acknowledgedBy: 'System Auto-Sentinel',
    resolved: true,
    resolvedAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
];
